/**
 * languages.js
 * Implements multilingual translation support for:
 * English (en), Hindi (hi), Spanish (es), French (fr), German (de).
 */

const translations = {
  en: {
    // Attendance & Profile
    present: "Present",
    absent: "Absent",
    half_day: "Half Day",
    leave: "Leave",
    attendance_rate: "Attendance Rate",
    present_today: "Present Today",
    absent_today: "Absent Today",
    days_worked: "Days Worked",
    days_absent: "Days Absent",
    days_on_leave: "Days on Leave",
    work_rate: "Work Rate",
    attendance: "Attendance",
    attendance_summary: "Attendance Summary",
    attendance_log: "Attendance Log",

    // Navigation
    dashboard: "Dashboard",
    employees: "Employees",
    salary_tracker: "Salary Tracker",
    loans_advances: "Loans & Advances",
    notes: "Notes",
    settings: "Settings",
    logout: "Logout",
    overview: "Overview",
    management: "Management",
    system: "System",
    admin: "Admin",

    // Dashboard Stats
    total_employees: "Total Employees",
    active_in_system: "Active in system",
    total_paid: "Total Paid",
    employees_paid: "employees paid",
    employee_paid: "employee paid",
    pending_salaries: "Pending Salaries",
    awaiting_payment: "awaiting payment",
    total_payroll: "Total Payroll",
    monthly_obligation: "Monthly obligation",
    total_loans_issued: "Total Loans Issued",
    loans: "loans",
    loan: "loan",
    outstanding_balance: "Outstanding Balance",
    remaining_to_repay: "Remaining to repay",
    employees_with_loans: "Employees with Loans",
    active_loans: "active loans",
    active_loan: "active loan",

    // Dashboard Sections
    recently_added: "Recently Added",
    view_all: "View all →",
    no_employees: "No employees yet",
    payment_overview: "Payment Overview",
    paid: "Paid",
    pending: "Pending",
    by_interval: "By Interval",
    recent_loans: "Recent Loans",
    manage_loans: "Manage loans →",
    no_loans: "No loans recorded yet",
    left: "left",
    total: "total",
    done: "Done",

    // Toolbar Filters
    search_placeholder: "Search by name, role, phone…",
    all_status: "All Status",
    unpaid: "Unpaid",
    all_intervals: "All Intervals",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    custom: "Custom",
    all_employees: "All Employees",
    has_active_loan: "Has Active Loan",
    no_active_loan: "No Active Loan",
    min: "Min",
    max: "Max",
    newest_first: "Newest First",
    oldest_first: "Oldest First",
    name_a_z: "Name A–Z",
    name_z_a: "Name Z–A",
    salary_high_low: "Salary High–Low",
    salary_low_high: "Salary Low–High",
    card_view: "Card View",
    table_view: "Table View",
    no_employees_found: "No employees found",
    adjust_filters: "Try adjusting filters or add a new employee",

    // Tables
    th_name: "Name",
    th_role: "Role",
    th_salary: "Salary",
    th_interval: "Interval",
    th_next_payment: "Next Payment",
    th_status: "Status",
    th_phone: "Phone",
    th_loan: "Loan",
    th_actions: "Actions",
    th_loan_deduct: "Loan Deduct.",
    th_net_pay: "Net Pay",
    th_last_paid: "Last Paid",
    th_toggle: "Toggle",
    th_employee: "Employee",
    th_repayments: "Repayments",

    // Salary Tracker Section
    paid_this_period: "Paid This Period",
    all_combined: "All employees combined",
    monthly_loan_deductions: "Monthly loan repayments",
    total_deductions: "Total Deductions",
    salary_details: "Salary Details",
    mark_all_paid: "Mark All Paid",
    reset_all: "Reset All",
    no_salary_records: "No salary records",
    add_employees_salary: "Add employees to track their salaries",

    // Loans & Advances
    issued: "Issued",
    outstanding: "Outstanding",
    active: "Active",
    completed: "Completed",
    repaying: "Currently repaying",
    fully_repaid: "Fully repaid",
    all: "All",
    add_loan: "Add Loan",
    no_loans_recorded: "No loans recorded",
    track_advances: "Track salary advances and loans for your employees",
    add_first_loan: "Add First Loan",

    // Notes
    no_notes: "No notes yet",
    add_notes_desc: "Add employees and write notes for each person",
    edit_note: "Edit Note",

    // Settings
    theme: "Theme",
    dark: "Dark",
    light: "Light",
    corporate: "Corporate",
    minimal: "Minimal",
    data_export: "Data Export",
    export_json: "Export JSON",
    export_csv: "Export CSV",
    account: "Account",
    display_name: "Display Name",
    save_changes: "Save Changes",
    clear_all_data: "Clear All Data",
    system_preferences: "System Preferences",
    language: "Language",
    currency: "Currency",

    // Modals
    add_employee: "Add Employee",
    edit_employee: "Edit Employee",
    cancel: "Cancel",
    save_employee: "Save Employee",
    full_name_req: "Full Name *",
    job_role_req: "Job / Role *",
    salary_amount_req: "Salary Amount *",
    payment_interval: "Payment Interval",
    custom_interval: "Custom Interval (days)",
    phone_opt: "Phone (optional)",
    payment_status: "Payment Status",
    notes_lbl: "Notes",
    notes_placeholder: "Any notes about this employee…",
    not_paid: "Not Paid",
    paid_badge: "Paid",
    write_notes_here: "Write notes here…",
    add_loan_advance: "Add Loan / Advance",
    employee_req: "Employee *",
    select_employee: "— Select Employee —",
    loan_amount_req: "Loan / Advance Amount *",
    date_given_req: "Date Given *",
    reason_opt: "Reason (optional)",
    repayment_type: "Repayment Type",
    fixed_monthly_deduct: "Fixed Monthly Deduction",
    manual_repay: "Manual Repayments",
    monthly_deduct_req: "Monthly Deduction Amount *",
    monthly_deduct_desc: "This will be deducted from salary each month until fully repaid.",
    save_loan: "Save Loan",
    loan_details: "Loan Details",
    repayment_history: "Repayment History",
    record_repayment: "Record a Repayment",
    amount_req: "Amount *",
    date: "Date",
    note_opt: "Note (optional)",
    add: "Add",
    close: "Close",
    delete_loan: "Delete Loan",
    confirm_title: "Are you sure?",
    confirm_text: "This action cannot be undone.",
    delete: "Delete",

    // Messages & Toasts
    toast_settings_saved: "Settings saved!",
    toast_data_cleared: "All data cleared.",
    toast_employee_updated: "Employee updated successfully.",
    toast_notes_saved: "Note saved!",
    toast_export_success: "Exported as {type}!",
    toast_repayment_recorded: "Repayment of {amt} recorded!",
    toast_loan_repaid: "Loan fully repaid! {name}'s loan is now complete.",
    toast_loan_deleted: "Loan deleted.",
    toast_loan_added: "Loan of {amt} added for {name}!",
    toast_theme_changed: "Theme changed to {theme}",
    toast_emp_removed: "{name} removed.",
    toast_emp_deleted: "Employee deleted.",
    toast_all_paid: "All employees marked as paid",
    toast_all_unpaid: "All employees reset to pending",
    toast_account_created: "Account created! Welcome, {name}!",
    toast_logged_out: "Logged out successfully.",
    toast_logged_in: "Logged in successfully.",
    toast_err_fields: "Please fill in all fields.",
    toast_err_pass: "Password must be at least 6 characters.",
    toast_err_email: "Please enter a valid email.",
    toast_err_exists: "An account with this email already exists.",
    toast_err_name: "Name is required.",
    toast_err_role: "Role is required.",
    toast_err_salary: "Please enter a valid salary.",
    toast_err_custom_days: "Please enter valid custom interval days.",
    toast_err_emp_select: "Please select an employee.",
    toast_err_loan_amt: "Please enter a valid loan amount.",
    toast_err_date: "Please select a date.",
    toast_err_monthly_deduct: "Please enter a valid monthly deduction amount.",
    toast_err_deduct_exceed: "Monthly deduction cannot exceed loan amount.",
    toast_err_emp_not_found: "Employee not found.",
    toast_err_repay_amt: "Please enter a valid repayment amount.",
    toast_err_already_repaid: "Loan is already fully repaid.",
    toast_err_no_export: "No data to export.",

    // Login screen demo credentials
    demo_credentials: "Demo: demo@workforce.app / demo1234",
    sign_in: "Sign In",
    create_account: "Create Account",
    welcome_back: "Welcome back",
    sign_in_manage: "Sign in to manage your workforce",
    start_managing: "Start managing your team today",
    full_name: "Full Name",
    email: "Email",
    password: "Password"
  },
  hi: {
    // Attendance & Profile
    present: "उपस्थित",
    absent: "अनुपस्थित",
    half_day: "आधा दिन",
    leave: "छुट्टी",
    attendance_rate: "उपस्थिति दर",
    present_today: "आज उपस्थित",
    absent_today: "आज अनुपस्थित",
    days_worked: "कार्य दिवस",
    days_absent: "अनुपस्थित दिवस",
    days_on_leave: "छुट्टी के दिन",
    work_rate: "कार्य दर",
    attendance: "उपस्थिति",
    attendance_summary: "उपस्थिति सारांश",
    attendance_log: "उपस्थिति लॉग",

    // Navigation
    dashboard: "डैशबोर्ड",
    employees: "कर्मचारी",
    salary_tracker: "वेतन ट्रैकर",
    loans_advances: "ऋण और अग्रिम",
    notes: "नोट्स",
    settings: "सेटिंग्स",
    logout: "लॉगआउट",
    overview: "अवलोकन",
    management: "प्रबंधन",
    system: "सिस्टम",
    admin: "एडमिन",

    // Dashboard Stats
    total_employees: "कुल कर्मचारी",
    active_in_system: "सिस्टम में सक्रिय",
    total_paid: "कुल भुगतान",
    employees_paid: "कर्मचारियों को भुगतान हुआ",
    employee_paid: "कर्मचारी को भुगतान हुआ",
    pending_salaries: "लंबित वेतन",
    awaiting_payment: "भुगतान की प्रतीक्षा में",
    total_payroll: "कुल पेरोल",
    monthly_obligation: "मासिक दायित्व",
    total_loans_issued: "कुल जारी ऋण",
    loans: "ऋण",
    loan: "ऋण",
    outstanding_balance: "बकाया राशि",
    remaining_to_repay: "चुकाने के लिए शेष",
    employees_with_loans: "ऋण वाले कर्मचारी",
    active_loans: "सक्रिय ऋण",
    active_loan: "सक्रिय ऋण",

    // Dashboard Sections
    recently_added: "हाल ही में जोड़े गए",
    view_all: "सभी देखें →",
    no_employees: "अभी तक कोई कर्मचारी नहीं है",
    payment_overview: "भुगतान का अवलोकन",
    paid: "भुगतान किया",
    pending: "लंबित",
    by_interval: "अंतराल के अनुसार",
    recent_loans: "हाल के ऋण",
    manage_loans: "ऋण प्रबंधित करें →",
    no_loans: "अभी तक कोई ऋण दर्ज नहीं है",
    left: "शेष",
    total: "कुल",
    done: "पूर्ण",

    // Toolbar Filters
    search_placeholder: "नाम, भूमिका, फोन से खोजें…",
    all_status: "सभी स्थिति",
    unpaid: "अवैतनिक",
    all_intervals: "सभी अंतराल",
    daily: "दैनिक",
    weekly: "साप्ताहिक",
    monthly: "मासिक",
    custom: "कस्टम",
    all_employees: "सभी कर्मचारी",
    has_active_loan: "सक्रिय ऋण है",
    no_active_loan: "कोई सक्रिय ऋण नहीं है",
    min: "न्यूनतम",
    max: "अधिकतम",
    newest_first: "नवीनतम पहले",
    oldest_first: "सबसे पुराना पहले",
    name_a_z: "नाम A–Z",
    name_z_a: "नाम Z–A",
    salary_high_low: "वेतन अधिक से कम",
    salary_low_high: "वेतन कम से अधिक",
    card_view: "कार्ड दृश्य",
    table_view: "तालिका दृश्य",
    no_employees_found: "कोई कर्मचारी नहीं मिला",
    adjust_filters: "फ़िल्टर समायोजित करें या नया कर्मचारी जोड़ें",

    // Tables
    th_name: "नाम",
    th_role: "भूमिका",
    th_salary: "वेतन",
    th_interval: "अंतराल",
    th_next_payment: "अगला भुगतान",
    th_status: "स्थिति",
    th_phone: "फ़ोन",
    th_loan: "ऋण",
    th_actions: "कार्रवाई",
    th_loan_deduct: "ऋण कटौती",
    th_net_pay: "कुल भुगतान",
    th_last_paid: "पिछला भुगतान",
    th_toggle: "टॉगल",
    th_employee: "कर्मचारी",
    th_repayments: "भुगतान रिकॉर्ड",

    // Salary Tracker Section
    paid_this_period: "इस अवधि में भुगतान किया",
    all_combined: "सभी कर्मचारी संयुक्त",
    monthly_loan_deductions: "मासिक ऋण भुगतान",
    total_deductions: "कुल कटौतियाँ",
    salary_details: "वेतन विवरण",
    mark_all_paid: "सभी को भुगतान करें",
    reset_all: "सभी रीसेट करें",
    no_salary_records: "कोई वेतन रिकॉर्ड नहीं",
    add_employees_salary: "उनके वेतन को ट्रैक करने के लिए कर्मचारी जोड़ें",

    // Loans & Advances
    issued: "जारी किया",
    outstanding: "बकाया",
    active: "सक्रिय",
    completed: "पूर्ण",
    repaying: "वर्तमान में चुका रहे हैं",
    fully_repaid: "पूरी तरह से चुकाया गया",
    all: "सभी",
    add_loan: "ऋण जोड़ें",
    no_loans_recorded: "कोई ऋण दर्ज नहीं",
    track_advances: "अपने कर्मचारियों के लिए वेतन अग्रिम और ऋण ट्रैक करें",
    add_first_loan: "पहला ऋण जोड़ें",

    // Notes
    no_notes: "अभी तक कोई नोट नहीं है",
    add_notes_desc: "कर्मचारी जोड़ें और प्रत्येक व्यक्ति के लिए नोट्स लिखें",
    edit_note: "नोट संपादित करें",

    // Settings
    theme: "थीम",
    dark: "डार्क",
    light: "लाइट",
    corporate: "कॉर्पोरेट",
    minimal: "मिनिमल",
    data_export: "डेटा निर्यात",
    export_json: "JSON निर्यात करें",
    export_csv: "CSV निर्यात करें",
    account: "खाता",
    display_name: "नाम प्रदर्शित करें",
    save_changes: "परिवर्तन सहेजें",
    clear_all_data: "सभी डेटा मिटाएं",
    system_preferences: "सिस्टम प्राथमिकताएं",
    language: "भाषा",
    currency: "मुद्रा",

    // Modals
    add_employee: "कर्मचारी जोड़ें",
    edit_employee: "कर्मचारी संपादित करें",
    cancel: "रद्द करें",
    save_employee: "कर्मचारी सहेजें",
    full_name_req: "पूरा नाम *",
    job_role_req: "कार्य / भूमिका *",
    salary_amount_req: "वेतन राशि *",
    payment_interval: "भुगतान अंतराल",
    custom_interval: "कस्टम अंतराल (दिन)",
    phone_opt: "फ़ोन (वैकल्पिक)",
    payment_status: "भुगतान की स्थिति",
    notes_lbl: "नोट्स",
    notes_placeholder: "इस कर्मचारी के बारे में कोई टिप्पणी…",
    not_paid: "भुगतान नहीं हुआ",
    paid_badge: "भुगतान हुआ",
    write_notes_here: "यहाँ नोट्स लिखें…",
    add_loan_advance: "ऋण / अग्रिम जोड़ें",
    employee_req: "कर्मचारी *",
    select_employee: "— कर्मचारी चुनें —",
    loan_amount_req: "ऋण / अग्रिम राशि *",
    date_given_req: "दी गई तारीख *",
    reason_opt: "कारण (वैकल्पिक)",
    repayment_type: "भुगतान प्रकार",
    fixed_monthly_deduct: "निश्चित मासिक कटौती",
    manual_repay: "मैनुअल भुगतान",
    monthly_deduct_req: "मासिक कटौती राशि *",
    monthly_deduct_desc: "पूरी तरह से चुकाए जाने तक इसे हर महीने वेतन से काटा जाएगा।",
    save_loan: "ऋण सहेजें",
    loan_details: "ऋण विवरण",
    repayment_history: "भुगतान का इतिहास",
    record_repayment: "एक पुनर्भुगतान दर्ज करें",
    amount_req: "राशि *",
    date: "तारीख",
    note_opt: "टिप्पणी (वैकल्पिक)",
    add: "जोड़ें",
    close: "बंद करें",
    delete_loan: "ऋण हटाएं",
    confirm_title: "क्या आप आश्वस्त हैं?",
    confirm_text: "इस कार्रवाई को पूर्ववत नहीं किया जा सकता।",
    delete: "हटाएं",

    // Messages & Toasts
    toast_settings_saved: "सेटिंग्स सहेजी गईं!",
    toast_data_cleared: "सारा डेटा साफ कर दिया गया।",
    toast_employee_updated: "कर्मचारी को सफलतापूर्वक अपडेट किया गया।",
    toast_notes_saved: "टिप्पणी सहेजी गई!",
    toast_export_success: "{type} के रूप में सफलतापूर्वक निर्यात किया गया!",
    toast_repayment_recorded: "{amt} का भुगतान दर्ज किया गया!",
    toast_loan_repaid: "ऋण पूरी तरह से चुकाया गया! {name} का ऋण अब पूरा हो गया है।",
    toast_loan_deleted: "ऋण हटा दिया गया।",
    toast_loan_added: "{name} के लिए {amt} का ऋण जोड़ा गया!",
    toast_theme_changed: "थीम बदलकर {theme} कर दी गई",
    toast_emp_removed: "{name} को हटा दिया गया।",
    toast_emp_deleted: "कर्मचारी को हटा दिया गया।",
    toast_all_paid: "सभी कर्मचारियों को भुगतान किया गया",
    toast_all_unpaid: "सभी कर्मचारियों की स्थिति लंबित की गई",
    toast_account_created: "खाता बन गया! आपका स्वागत है, {name}!",
    toast_logged_out: "लॉगआउट सफल रहा।",
    toast_logged_in: "लॉगिन सफल रहा।",
    toast_err_fields: "कृपया सभी फ़ील्ड भरें।",
    toast_err_pass: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",
    toast_err_email: "कृपया एक मान्य ईमेल दर्ज करें।",
    toast_err_exists: "इस ईमेल वाला खाता पहले से मौजूद है।",
    toast_err_name: "नाम आवश्यक है।",
    toast_err_role: "भूमिका आवश्यक है।",
    toast_err_salary: "कृपया एक मान्य वेतन दर्ज करें।",
    toast_err_custom_days: "कृपया मान्य कस्टम अंतराल दिन दर्ज करें।",
    toast_err_emp_select: "कृपया एक कर्मचारी चुनें।",
    toast_err_loan_amt: "कृपया मान्य ऋण राशि दर्ज करें।",
    toast_err_date: "कृपया एक तारीख चुनें।",
    toast_err_monthly_deduct: "कृपया एक मान्य मासिक कटौती राशि दर्ज करें।",
    toast_err_deduct_exceed: "मासिक कटौती ऋण राशि से अधिक नहीं हो सकती।",
    toast_err_emp_not_found: "कर्मचारी नहीं मिला।",
    toast_err_repay_amt: "कृपया एक मान्य भुगतान राशि दर्ज करें।",
    toast_err_already_repaid: "ऋण पहले ही पूरी तरह से चुकाया जा चुका है।",
    toast_err_no_export: "निर्यात करने के लिए कोई डेटा नहीं है।",

    // Login screen
    demo_credentials: "डेमो: demo@workforce.app / demo1234",
    sign_in: "साइन इन करें",
    create_account: "खाता बनाएं",
    welcome_back: "स्वागत है",
    sign_in_manage: "अपनी कार्यबल को प्रबंधित करने के लिए साइन इन करें",
    start_managing: "आज ही अपनी टीम का प्रबंधन शुरू करें",
    full_name: "पूरा नाम",
    email: "ईमेल",
    password: "पासवर्ड"
  },
  es: {
    // Attendance & Profile
    present: "Presente",
    absent: "Ausente",
    half_day: "Medio Día",
    leave: "Licencia",
    attendance_rate: "Tasa de Asistencia",
    present_today: "Presentes Hoy",
    absent_today: "Ausentes Hoy",
    days_worked: "Días Trabajados",
    days_absent: "Días Ausentes",
    days_on_leave: "Días de Licencia",
    work_rate: "Tasa de Trabajo",
    attendance: "Asistencia",
    attendance_summary: "Resumen de Asistencia",
    attendance_log: "Registro de Asistencia",

    // Navigation
    dashboard: "Tablero",
    employees: "Empleados",
    salary_tracker: "Control de Salarios",
    loans_advances: "Préstamos y Anticipos",
    notes: "Notas",
    settings: "Configuración",
    logout: "Cerrar Sesión",
    overview: "Resumen",
    management: "Gestión",
    system: "Sistema",
    admin: "Admin",

    // Dashboard Stats
    total_employees: "Empleados Totales",
    active_in_system: "Activos en el sistema",
    total_paid: "Total Pagado",
    employees_paid: "empleados pagados",
    employee_paid: "empleado pagado",
    pending_salaries: "Salarios Pendientes",
    awaiting_payment: "esperando pago",
    total_payroll: "Nómina Total",
    monthly_obligation: "Obligación mensual",
    total_loans_issued: "Total Préstamos Emitidos",
    loans: "préstamos",
    loan: "préstamo",
    outstanding_balance: "Saldo Pendiente",
    remaining_to_repay: "Restante por pagar",
    employees_with_loans: "Empleados con Préstamo",
    active_loans: "préstamos activos",
    active_loan: "préstamo activo",

    // Dashboard Sections
    recently_added: "Agregados Recientemente",
    view_all: "Ver todos →",
    no_employees: "No hay empleados aún",
    payment_overview: "Resumen de Pagos",
    paid: "Pagado",
    pending: "Pendiente",
    by_interval: "Por Intervalo",
    recent_loans: "Préstamos Recientes",
    manage_loans: "Gestionar préstamos →",
    no_loans: "No hay préstamos registrados aún",
    left: "restante",
    total: "total",
    done: "Listo",

    // Toolbar Filters
    search_placeholder: "Buscar por nombre, cargo, teléfono…",
    all_status: "Todos los Estados",
    unpaid: "No Pagado",
    all_intervals: "Todos los Intervalos",
    daily: "Diario",
    weekly: "Semanal",
    monthly: "Mensual",
    custom: "Personalizado",
    all_employees: "Todos los Empleados",
    has_active_loan: "Tiene Préstamo Activo",
    no_active_loan: "Sin Préstamo Activo",
    min: "Mín",
    max: "Máx",
    newest_first: "Más Recientes Primero",
    oldest_first: "Más Antiguos Primero",
    name_a_z: "Nombre A–Z",
    name_z_a: "Nombre Z–A",
    salary_high_low: "Salario Alto–Bajo",
    salary_low_high: "Salario Bajo–Alto",
    card_view: "Vista Tarjeta",
    table_view: "Vista Tabla",
    no_employees_found: "No se encontraron empleados",
    adjust_filters: "Intente ajustar los filtros o agregue un nuevo empleado",

    // Tables
    th_name: "Nombre",
    th_role: "Cargo",
    th_salary: "Salario",
    th_interval: "Intervalo",
    th_next_payment: "Siguiente Pago",
    th_status: "Estado",
    th_phone: "Teléfono",
    th_loan: "Préstamo",
    th_actions: "Acciones",
    th_loan_deduct: "Deducción Préstamo",
    th_net_pay: "Pago Neto",
    th_last_paid: "Último Pago",
    th_toggle: "Alternar",
    th_employee: "Empleado",
    th_repayments: "Historial Repagos",

    // Salary Tracker Section
    paid_this_period: "Pagado en este Período",
    all_combined: "Todos los empleados combinados",
    monthly_loan_deductions: "Deducciones de préstamos",
    total_deductions: "Deducciones Totales",
    salary_details: "Detalles del Salario",
    mark_all_paid: "Marcar Todos como Pagados",
    reset_all: "Restablecer Todos",
    no_salary_records: "Sin registros de salario",
    add_employees_salary: "Agregue empleados para rastrear sus salarios",

    // Loans & Advances
    issued: "Emitido",
    outstanding: "Pendiente",
    active: "Activo",
    completed: "Completado",
    repaying: "Pagando actualmente",
    fully_repaid: "Totalmente pagado",
    all: "Todos",
    add_loan: "Agregar Préstamo",
    no_loans_recorded: "Sin préstamos registrados",
    track_advances: "Rastree anticipos de salarios y préstamos para sus empleados",
    add_first_loan: "Agregar Primer Préstamo",

    // Notes
    no_notes: "Sin notas aún",
    add_notes_desc: "Agregue empleados y escriba notas para cada persona",
    edit_note: "Editar Nota",

    // Settings
    theme: "Tema",
    dark: "Oscuro",
    light: "Claro",
    corporate: "Corporativo",
    minimal: "Minimalista",
    data_export: "Exportar Datos",
    export_json: "Exportar JSON",
    export_csv: "Exportar CSV",
    account: "Cuenta",
    display_name: "Nombre a Mostrar",
    save_changes: "Guardar Cambios",
    clear_all_data: "Borrar Todos los Datos",
    system_preferences: "Preferencias del Sistema",
    language: "Idioma",
    currency: "Moneda",

    // Modals
    add_employee: "Agregar Empleado",
    edit_employee: "Editar Empleado",
    cancel: "Cancelar",
    save_employee: "Guardar Empleado",
    full_name_req: "Nombre Completo *",
    job_role_req: "Puesto / Cargo *",
    salary_amount_req: "Monto del Salario *",
    payment_interval: "Intervalo de Pago",
    custom_interval: "Intervalo Personalizado (días)",
    phone_opt: "Teléfono (opcional)",
    payment_status: "Estado del Pago",
    notes_lbl: "Notas",
    notes_placeholder: "Cualquier nota sobre este empleado…",
    not_paid: "No Pagado",
    paid_badge: "Pagado",
    write_notes_here: "Escriba notas aquí…",
    add_loan_advance: "Agregar Préstamo / Anticipo",
    employee_req: "Empleado *",
    select_employee: "— Seleccionar Empleado —",
    loan_amount_req: "Monto del Préstamo *",
    date_given_req: "Fecha Otorgado *",
    reason_opt: "Razón (opcional)",
    repayment_type: "Tipo de Pago",
    fixed_monthly_deduct: "Deducción Mensual Fija",
    manual_repay: "Pagos Manuales",
    monthly_deduct_req: "Monto Deducción Mensual *",
    monthly_deduct_desc: "Se deducirá del salario cada mes hasta su total reembolso.",
    save_loan: "Guardar Préstamo",
    loan_details: "Detalles del Préstamo",
    repayment_history: "Historial de Pagos",
    record_repayment: "Registrar un Pago",
    amount_req: "Monto *",
    date: "Fecha",
    note_opt: "Nota (opcional)",
    add: "Agregar",
    close: "Cerrar",
    delete_loan: "Eliminar Préstamo",
    confirm_title: "¿Está seguro?",
    confirm_text: "Esta acción no se puede deshacer.",
    delete: "Eliminar",

    // Messages & Toasts
    toast_settings_saved: "¡Configuración guardada!",
    toast_data_cleared: "Todos los datos borrados.",
    toast_employee_updated: "Empleado actualizado correctamente.",
    toast_notes_saved: "¡Nota guardada!",
    toast_export_success: "¡Exportado como {type} correctamente!",
    toast_repayment_recorded: "¡Pago de {amt} registrado!",
    toast_loan_repaid: "¡Préstamo totalmente pagado! El préstamo de {name} ha concluido.",
    toast_loan_deleted: "Préstamo eliminado.",
    toast_loan_added: "¡Préstamo de {amt} agregado para {name}!",
    toast_theme_changed: "Tema cambiado a {theme}",
    toast_emp_removed: "{name} eliminado.",
    toast_emp_deleted: "Empleado eliminado.",
    toast_all_paid: "Todos los empleados marcados como pagados",
    toast_all_unpaid: "Todos los empleados restablecidos a pendientes",
    toast_account_created: "¡Cuenta creada! Bienvenido, {name}!",
    toast_logged_out: "Sesión cerrada correctamente.",
    toast_logged_in: "Sesión iniciada correctamente.",
    toast_err_fields: "Por favor complete todos los campos.",
    toast_err_pass: "La contraseña debe tener al menos 6 caracteres.",
    toast_err_email: "Por favor introduzca un correo electrónico válido.",
    toast_err_exists: "Ya existe una cuenta con este correo.",
    toast_err_name: "El nombre es obligatorio.",
    toast_err_role: "El cargo es obligatorio.",
    toast_err_salary: "Por favor introduzca un salario válido.",
    toast_err_custom_days: "Por favor introduzca días válidos para el intervalo personalizado.",
    toast_err_emp_select: "Por favor seleccione un empleado.",
    toast_err_loan_amt: "Por favor introduzca un monto de préstamo válido.",
    toast_err_date: "Por favor seleccione una fecha.",
    toast_err_monthly_deduct: "Por favor introduzca un monto de deducción mensual válido.",
    toast_err_deduct_exceed: "La deducción mensual no puede superar el monto del préstamo.",
    toast_err_emp_not_found: "Empleado no encontrado.",
    toast_err_repay_amt: "Por favor introduzca un monto de pago válido.",
    toast_err_already_repaid: "El préstamo ya está totalmente pagado.",
    toast_err_no_export: "No hay datos para exportar.",

    // Login screen
    demo_credentials: "Demo: demo@workforce.app / demo1234",
    sign_in: "Iniciar Sesión",
    create_account: "Crear Cuenta",
    welcome_back: "Bienvenido",
    sign_in_manage: "Inicie sesión para gestionar su personal",
    start_managing: "Comience a gestionar su equipo hoy",
    full_name: "Nombre Completo",
    email: "Correo Electrónico",
    password: "Contraseña"
  },
  fr: {
    // Attendance & Profile
    present: "Présent",
    absent: "Absent",
    half_day: "Demi-journée",
    leave: "Congé",
    attendance_rate: "Taux de Présence",
    present_today: "Présents Aujourd'hui",
    absent_today: "Absents Aujourd'hui",
    days_worked: "Jours Travaillés",
    days_absent: "Jours Absents",
    days_on_leave: "Jours de Congé",
    work_rate: "Taux de Travail",
    attendance: "Présence",
    attendance_summary: "Résumé de Présence",
    attendance_log: "Registre de Présence",

    // Navigation
    dashboard: "Tableau de Bord",
    employees: "Employés",
    salary_tracker: "Suivi des Salaires",
    loans_advances: "Prêts & Avances",
    notes: "Notes",
    settings: "Paramètres",
    logout: "Se Déconnecter",
    overview: "Aperçu",
    management: "Gestion",
    system: "Système",
    admin: "Admin",

    // Dashboard Stats
    total_employees: "Total Employés",
    active_in_system: "Actifs dans le système",
    total_paid: "Total Payé",
    employees_paid: "employés payés",
    employee_paid: "employé payé",
    pending_salaries: "Salaires en Attente",
    awaiting_payment: "en attente de paiement",
    total_payroll: "Masse Salariale",
    monthly_obligation: "Obligation mensuelle",
    total_loans_issued: "Total Prêts Accordés",
    loans: "prêts",
    loan: "prêt",
    outstanding_balance: "Solde Restant",
    remaining_to_repay: "Reste à rembourser",
    employees_with_loans: "Employés avec Prêt",
    active_loans: "prêts actifs",
    active_loan: "prêt actif",

    // Dashboard Sections
    recently_added: "Récemment Ajoutés",
    view_all: "Voir tout →",
    no_employees: "Pas encore d'employés",
    payment_overview: "Aperçu des Paiements",
    paid: "Payé",
    pending: "En attente",
    by_interval: "Par Intervalle",
    recent_loans: "Prêts Récents",
    manage_loans: "Gérer les prêts →",
    no_loans: "Aucun prêt enregistré",
    left: "restant",
    total: "total",
    done: "Terminé",

    // Toolbar Filters
    search_placeholder: "Rechercher par nom, rôle, tel…",
    all_status: "Tous les Statuts",
    unpaid: "Non Payé",
    all_intervals: "Tous les Intervalles",
    daily: "Journalier",
    weekly: "Hebdomadaire",
    monthly: "Mensuel",
    custom: "Personnalisé",
    all_employees: "Tous les Employés",
    has_active_loan: "A un Prêt Actif",
    no_active_loan: "Sans Prêt Actif",
    min: "Min",
    max: "Max",
    newest_first: "Plus Récents d'abord",
    oldest_first: "Plus Anciens d'abord",
    name_a_z: "Nom A–Z",
    name_z_a: "Nom Z–A",
    salary_high_low: "Salaire Élevé–Bas",
    salary_low_high: "Salaire Bas–Élevé",
    card_view: "Vue Cartes",
    table_view: "Vue Tableau",
    no_employees_found: "Aucun employé trouvé",
    adjust_filters: "Essayez d'ajuster les filtres ou ajoutez un nouvel employé",

    // Tables
    th_name: "Nom",
    th_role: "Rôle",
    th_salary: "Salaire",
    th_interval: "Intervalle",
    th_next_payment: "Prochain Paiement",
    th_status: "Statut",
    th_phone: "Téléphone",
    th_loan: "Prêt",
    th_actions: "Actions",
    th_loan_deduct: "Déduction Prêt",
    th_net_pay: "Salaire Net",
    th_last_paid: "Dernier Payé",
    th_toggle: "Bouton",
    th_employee: "Employé",
    th_repayments: "Remboursements",

    // Salary Tracker Section
    paid_this_period: "Payé cette Période",
    all_combined: "Tous les employés combinés",
    monthly_loan_deductions: "Remboursements mensuels",
    total_deductions: "Total Déductions",
    salary_details: "Détails du Salaire",
    mark_all_paid: "Marquer Tout Payé",
    reset_all: "Tout Réinitialiser",
    no_salary_records: "Aucun enregistrement",
    add_employees_salary: "Ajoutez des employés pour suivre leurs salaires",

    // Loans & Advances
    issued: "Émis",
    outstanding: "Restant",
    active: "Actif",
    completed: "Terminé",
    repaying: "En cours de remboursement",
    fully_repaid: "Entièrement remboursé",
    all: "Tous",
    add_loan: "Ajouter Prêt",
    no_loans_recorded: "Aucun prêt enregistré",
    track_advances: "Suivez les avances sur salaire et les prêts de vos employés",
    add_first_loan: "Ajouter Premier Prêt",

    // Notes
    no_notes: "Pas encore de notes",
    add_notes_desc: "Ajoutez des employés et écrivez des notes pour chacun",
    edit_note: "Modifier la Note",

    // Settings
    theme: "Thème",
    dark: "Sombre",
    light: "Clair",
    corporate: "Professionnel",
    minimal: "Minimaliste",
    data_export: "Exporter les Données",
    export_json: "Exporter JSON",
    export_csv: "Exporter CSV",
    account: "Compte",
    display_name: "Nom d'affichage",
    save_changes: "Enregistrer",
    clear_all_data: "Effacer Toutes les Données",
    system_preferences: "Préférences Système",
    language: "Langue",
    currency: "Devise",

    // Modals
    add_employee: "Ajouter Employé",
    edit_employee: "Modifier Employé",
    cancel: "Annuler",
    save_employee: "Enregistrer l'Employé",
    full_name_req: "Nom Complet *",
    job_role_req: "Poste / Rôle *",
    salary_amount_req: "Montant du Salaire *",
    payment_interval: "Intervalle de Paiement",
    custom_interval: "Intervalle Perso (jours)",
    phone_opt: "Téléphone (optionnel)",
    payment_status: "Statut du Paiement",
    notes_lbl: "Notes",
    notes_placeholder: "Notes concernant cet employé…",
    not_paid: "Non Payé",
    paid_badge: "Payé",
    write_notes_here: "Écrire les notes ici…",
    add_loan_advance: "Ajouter Prêt / Avance",
    employee_req: "Employé *",
    select_employee: "— Sélectionner Employé —",
    loan_amount_req: "Montant du Prêt *",
    date_given_req: "Date d'Attribution *",
    reason_opt: "Motif (optionnel)",
    repayment_type: "Type de Remboursement",
    fixed_monthly_deduct: "Déduction Mensuelle Fixe",
    manual_repay: "Remboursements Manuels",
    monthly_deduct_req: "Montant Déduction Mensuelle *",
    monthly_deduct_desc: "Ce montant sera déduit du salaire chaque mois jusqu'au remboursement total.",
    save_loan: "Enregistrer le Prêt",
    loan_details: "Détails du Prêt",
    repayment_history: "Historique des Paiements",
    record_repayment: "Enregistrer un Remboursement",
    amount_req: "Montant *",
    date: "Date",
    note_opt: "Note (optionnel)",
    add: "Ajouter",
    close: "Fermer",
    delete_loan: "Supprimer le Prêt",
    confirm_title: "Êtes-vous sûr ?",
    confirm_text: "Cette action ne peut pas être annulée.",
    delete: "Supprimer",

    // Messages & Toasts
    toast_settings_saved: "Paramètres enregistrés !",
    toast_data_cleared: "Toutes les données ont été effacées.",
    toast_employee_updated: "Employé mis à jour avec succès.",
    toast_notes_saved: "Note enregistrée !",
    toast_export_success: "Exporté sous format {type} avec succès !",
    toast_repayment_recorded: "Remboursement de {amt} enregistré !",
    toast_loan_repaid: "Prêt entièrement remboursé ! Le prêt de {name} est terminé.",
    toast_loan_deleted: "Prêt supprimé.",
    toast_loan_added: "Prêt de {amt} ajouté pour {name} !",
    toast_theme_changed: "Thème changé pour {theme}",
    toast_emp_removed: "{name} supprimé.",
    toast_emp_deleted: "Employé supprimé.",
    toast_all_paid: "Tous les employés sont marqués comme payés",
    toast_all_unpaid: "Tous les employés sont réinitialisés en attente",
    toast_account_created: "Compte créé ! Bienvenue, {name} !",
    toast_logged_out: "Déconnexion réussie.",
    toast_logged_in: "Connexion réussie.",
    toast_err_fields: "Veuillez remplir tous les champs.",
    toast_err_pass: "Le mot de passe doit contenir au moins 6 caractères.",
    toast_err_email: "Veuillez saisir une adresse e-mail valide.",
    toast_err_exists: "Un compte avec cet e-mail existe déjà.",
    toast_err_name: "Le nom est obligatoire.",
    toast_err_role: "Le rôle est obligatoire.",
    toast_err_salary: "Veuillez saisir un salaire valide.",
    toast_err_custom_days: "Veuillez saisir un nombre de jours valide.",
    toast_err_emp_select: "Veuillez sélectionner un employé.",
    toast_err_loan_amt: "Veuillez saisir un montant de prêt valide.",
    toast_err_date: "Veuillez sélectionner une date.",
    toast_err_monthly_deduct: "Veuillez saisir un montant de déduction mensuelle valide.",
    toast_err_deduct_exceed: "La déduction mensuelle ne peut pas dépasser le montant du prêt.",
    toast_err_emp_not_found: "Employé non trouvé.",
    toast_err_repay_amt: "Veuillez saisir un montant de remboursement valide.",
    toast_err_already_repaid: "Le prêt est déjà entièrement remboursé.",
    toast_err_no_export: "Aucune donnée à exporter.",

    // Login screen
    demo_credentials: "Démo : demo@workforce.app / demo1234",
    sign_in: "Se Connecter",
    create_account: "Créer un Compte",
    welcome_back: "Bienvenue",
    sign_in_manage: "Connectez-vous pour gérer vos effectifs",
    start_managing: "Commencez à gérer votre équipe dès aujourd'hui",
    full_name: "Nom Complet",
    email: "E-mail",
    password: "Mot de passe"
  },
  de: {
    // Attendance & Profile
    present: "Anwesend",
    absent: "Abwesend",
    half_day: "Halber Tag",
    leave: "Urlaub",
    attendance_rate: "Anwesenheitsquote",
    present_today: "Heute Anwesend",
    absent_today: "Heute Abwesend",
    days_worked: "Arbeitstage",
    days_absent: "Fehltage",
    days_on_leave: "Urlaubstage",
    work_rate: "Arbeitsquote",
    attendance: "Anwesenheit",
    attendance_summary: "Anwesenheitszusammenfassung",
    attendance_log: "Anwesenheitsprotokoll",

    // Navigation
    dashboard: "Dashboard",
    employees: "Mitarbeiter",
    salary_tracker: "Gehalts-Tracker",
    loans_advances: "Kredite & Vorschüsse",
    notes: "Notizen",
    settings: "Einstellungen",
    logout: "Abmelden",
    overview: "Übersicht",
    management: "Verwaltung",
    system: "System",
    admin: "Admin",

    // Dashboard Stats
    total_employees: "Mitarbeiter Gesamt",
    active_in_system: "Aktiv im System",
    total_paid: "Ausgezahlt Gesamt",
    employees_paid: "Mitarbeiter bezahlt",
    employee_paid: "Mitarbeiter bezahlt",
    pending_salaries: "Ausstehende Gehälter",
    awaiting_payment: "warten auf Zahlung",
    total_payroll: "Gesamt-Lohnsumme",
    monthly_obligation: "Monatliche Verpflichtung",
    total_loans_issued: "Vergebene Kredite Gesamt",
    loans: "Kredite",
    loan: "Kredit",
    outstanding_balance: "Offener Kreditsaldo",
    remaining_to_repay: "Noch zurückzuzahlen",
    employees_with_loans: "Mitarbeiter mit Krediten",
    active_loans: "aktive Kredite",
    active_loan: "aktiver Kredit",

    // Dashboard Sections
    recently_added: "Zuletzt Hinzugefügt",
    view_all: "Alle anzeigen →",
    no_employees: "Noch keine Mitarbeiter",
    payment_overview: "Zahlungsübersicht",
    paid: "Bezahlt",
    pending: "Ausstehend",
    by_interval: "Nach Intervall",
    recent_loans: "Aktuelle Kredite",
    manage_loans: "Kredite verwalten →",
    no_loans: "Noch keine Kredite erfasst",
    left: "übrig",
    total: "gesamt",
    done: "Erledigt",

    // Toolbar Filters
    search_placeholder: "Suche nach Name, Rolle, Tel…",
    all_status: "Alle Status",
    unpaid: "Unbezahlt",
    all_intervals: "Alle Intervalle",
    daily: "Täglich",
    weekly: "Wöchentlich",
    monthly: "Monatlich",
    custom: "Benutzerdefiniert",
    all_employees: "Alle Mitarbeiter",
    has_active_loan: "Hat aktiven Kredit",
    no_active_loan: "Kein aktiver Kredit",
    min: "Min",
    max: "Max",
    newest_first: "Neueste zuerst",
    oldest_first: "Älteste zuerst",
    name_a_z: "Name A–Z",
    name_z_a: "Name Z–A",
    salary_high_low: "Gehalt Hoch–Tief",
    salary_low_high: "Gehalt Tief–Hoch",
    card_view: "Kartenansicht",
    table_view: "Tabellenansicht",
    no_employees_found: "Keine Mitarbeiter gefunden",
    adjust_filters: "Passen Sie die Filter an oder fügen Sie einen neuen Mitarbeiter hinzu",

    // Tables
    th_name: "Name",
    th_role: "Rolle",
    th_salary: "Gehalt",
    th_interval: "Intervall",
    th_next_payment: "Nächste Zahlung",
    th_status: "Status",
    th_phone: "Telefon",
    th_loan: "Kredit",
    th_actions: "Aktionen",
    th_loan_deduct: "Kreditabzug",
    th_net_pay: "Nettogehalt",
    th_last_paid: "Zuletzt Bezahlt",
    th_toggle: "Schalter",
    th_employee: "Mitarbeiter",
    th_repayments: "Rückzahlungen",

    // Salary Tracker Section
    paid_this_period: "In dieser Periode bezahlt",
    all_combined: "Alle Mitarbeiter zusammen",
    monthly_loan_deductions: "Monatliche Kreditraten",
    total_deductions: "Abzüge Gesamt",
    salary_details: "Gehaltsdetails",
    mark_all_paid: "Alle als bezahlt markieren",
    reset_all: "Alle zurücksetzen",
    no_salary_records: "Keine Gehaltsdaten",
    add_employees_salary: "Fügen Sie Mitarbeiter hinzu, um deren Gehälter zu verfolgen",

    // Loans & Advances
    issued: "Vergeben",
    outstanding: "Ausstehend",
    active: "Aktiv",
    completed: "Abgeschlossen",
    repaying: "Aktuelle Rückzahlung",
    fully_repaid: "Vollständig zurückgezahlt",
    all: "Alle",
    add_loan: "Kredit hinzufügen",
    no_loans_recorded: "Keine Kredite erfasst",
    track_advances: "Verfolgen Sie Gehaltsvorschüsse und Kredite für Ihre Mitarbeiter",
    add_first_loan: "Ersten Kredit hinzufügen",

    // Notes
    no_notes: "Noch keine Notizen",
    add_notes_desc: "Fügen Sie Mitarbeiter hinzu, um Notizen zu schreiben",
    edit_note: "Notiz bearbeiten",

    // Settings
    theme: "Theme",
    dark: "Dunkel",
    light: "Hell",
    corporate: "Unternehmen",
    minimal: "Minimalistisch",
    data_export: "Datenexport",
    export_json: "JSON exportieren",
    export_csv: "CSV exportieren",
    account: "Konto",
    display_name: "Anzeigename",
    save_changes: "Änderungen speichern",
    clear_all_data: "Alle Daten löschen",
    system_preferences: "Systemeinstellungen",
    language: "Sprache",
    currency: "Währung",

    // Modals
    add_employee: "Mitarbeiter hinzufügen",
    edit_employee: "Mitarbeiter bearbeiten",
    cancel: "Abbrechen",
    save_employee: "Mitarbeiter speichern",
    full_name_req: "Vollständiger Name *",
    job_role_req: "Job / Rolle *",
    salary_amount_req: "Gehaltshöhe *",
    payment_interval: "Zahlungsintervall",
    custom_interval: "Eigener Intervall (Tage)",
    phone_opt: "Telefon (optional)",
    payment_status: "Zahlungsstatus",
    notes_lbl: "Notizen",
    notes_placeholder: "Beliebige Notizen zum Mitarbeiter…",
    not_paid: "Nicht bezahlt",
    paid_badge: "Bezahlt",
    write_notes_here: "Notizen hier schreiben…",
    add_loan_advance: "Kredit / Vorschuss hinzufügen",
    employee_req: "Mitarbeiter *",
    select_employee: "— Mitarbeiter auswählen —",
    loan_amount_req: "Kredit- / Vorschussbetrag *",
    date_given_req: "Vergabedatum *",
    reason_opt: "Grund (optional)",
    repayment_type: "Rückzahlungsart",
    fixed_monthly_deduct: "Fester monatlicher Abzug",
    manual_repay: "Manuelle Rückzahlungen",
    monthly_deduct_req: "Monatlicher Abzugsbetrag *",
    monthly_deduct_desc: "Dieser Betrag wird jeden Monat vom Gehalt abgezogen, bis er vollständig zurückgezahlt ist.",
    save_loan: "Kredit speichern",
    loan_details: "Kreditdetails",
    repayment_history: "Rückzahlungshistorie",
    record_repayment: "Rückzahlung erfassen",
    amount_req: "Betrag *",
    date: "Datum",
    note_opt: "Notiz (optional)",
    add: "Hinzufügen",
    close: "Schließen",
    delete_loan: "Kredit löschen",
    confirm_title: "Sind Sie sicher?",
    confirm_text: "Diese Aktion kann nicht rückgängig gemacht werden.",
    delete: "Löschen",

    // Messages & Toasts
    toast_settings_saved: "Einstellungen gespeichert!",
    toast_data_cleared: "Alle Daten gelöscht.",
    toast_employee_updated: "Mitarbeiter erfolgreich aktualisiert.",
    toast_notes_saved: "Notiz gespeichert!",
    toast_export_success: "Erfolgreich als {type} exportiert!",
    toast_repayment_recorded: "Rückzahlung von {amt} erfasst!",
    toast_loan_repaid: "Kredit vollständig zurückgezahlt! {name}s Kredit ist nun abgeschlossen.",
    toast_loan_deleted: "Kredit gelöscht.",
    toast_loan_added: "Kredit über {amt} für {name} hinzugefügt!",
    toast_theme_changed: "Theme in {theme} geändert",
    toast_emp_removed: "{name} entfernt.",
    toast_emp_deleted: "Mitarbeiter gelöscht.",
    toast_all_paid: "Alle Mitarbeiter als bezahlt markiert",
    toast_all_unpaid: "Alle Mitarbeiter zurückgesetzt",
    toast_account_created: "Konto erstellt! Willkommen, {name}!",
    toast_logged_out: "Erfolgreich abgemeldet.",
    toast_logged_in: "Erfolgreich angemeldet.",
    toast_err_fields: "Bitte füllen Sie alle Felder aus.",
    toast_err_pass: "Das Passwort muss mindestens 6 Zeichen lang sein.",
    toast_err_email: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
    toast_err_exists: "Ein Konto mit dieser E-Mail existiert bereits.",
    toast_err_name: "Name ist erforderlich.",
    toast_err_role: "Rolle ist erforderlich.",
    toast_err_salary: "Bitte geben Sie ein gültiges Gehalt ein.",
    toast_err_custom_days: "Bitte geben Sie gültige Tage für das Intervall ein.",
    toast_err_emp_select: "Bitte wählen Sie einen Mitarbeiter aus.",
    toast_err_loan_amt: "Bitte geben Sie eine gültige Kreditsumme ein.",
    toast_err_date: "Bitte wählen Sie ein Datum aus.",
    toast_err_monthly_deduct: "Bitte geben Sie einen gültigen monatlichen Abzug ein.",
    toast_err_deduct_exceed: "Der monatliche Abzug darf die Kreditsumme nicht überschreiten.",
    toast_err_emp_not_found: "Mitarbeiter nicht gefunden.",
    toast_err_repay_amt: "Bitte geben Sie einen gültigen Rückzahlungsbetrag ein.",
    toast_err_already_repaid: "Kredit ist bereits vollständig zurückgezahlt.",
    toast_err_no_export: "Keine Daten zum Exportieren vorhanden.",

    // Login screen
    demo_credentials: "Demo: demo@workforce.app / demo1234",
    sign_in: "Anmelden",
    create_account: "Konto erstellen",
    welcome_back: "Willkommen zurück",
    sign_in_manage: "Melden Sie sich an, um Ihre Mitarbeiter zu verwalten",
    start_managing: "Beginnen Sie noch heute mit der Verwaltung Ihres Teams",
    full_name: "Vollständiger Name",
    email: "E-Mail",
    password: "Passwort"
  }
};

/**
 * Translates a key using variables interpolation.
 * @param {string} key - Translation key.
 * @param {Object} [vars] - Variables context.
 * @returns {string} Translated string.
 */
function t(key, vars = {}) {
  const lang = getLanguage();
  const dict = translations[lang] || translations.en;
  let text = dict[key] || translations.en[key] || key;

  // Perform variables replacement
  Object.keys(vars).forEach(k => {
    text = text.replace(new RegExp(`{${k}}`, 'g'), vars[k]);
  });
  return text;
}

/**
 * Scans the DOM for data-i18n and data-i18n-placeholder elements and translates them.
 */
function translateDOM() {
  const lang = getLanguage();
  
  // Translate standard textContent elements
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    el.textContent = t(key);
  });

  // Translate inputs placeholders
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    el.setAttribute('placeholder', t(key));
  });

  // Special UI dynamic elements that require manual updates
  // Translate the page title based on settings
  const pageTitles = {
    dashboard: t('dashboard'),
    employees: t('employees'),
    salary: t('salary_tracker'),
    loans: t('loans_advances'),
    notes: t('notes'),
    settings: t('settings')
  };
  const titleEl = document.getElementById('topbar-title');
  if (titleEl && pageTitles[currentPage]) {
    titleEl.textContent = pageTitles[currentPage];
  }
}

/**
 * Changes language preference, writes to localStorage, and updates UI layouts.
 * @param {string} lang - Language code ('en', 'hi', 'es', 'fr', 'de').
 */
function changeLanguage(lang) {
  saveLanguage(lang);
  
  // Force DOM re-translation
  translateDOM();
  
  // Update Settings page selections if visible
  const langSelect = document.getElementById('settings-lang');
  if (langSelect) {
    langSelect.value = lang;
  }

  // Refresh active screen state
  if (currentPage === 'dashboard') renderDashboard();
  else if (currentPage === 'employees') renderEmployees();
  else if (currentPage === 'salary') renderSalary();
  else if (currentPage === 'loans') renderLoans();
  else if (currentPage === 'notes') renderNotes();
  else if (currentPage === 'settings') renderSettings();

  showToast(t('toast_settings_saved'), 'success');
}
